name: build-go-binary

on:
  release:
    types: [ created ] # 表示在创建新的 Release 时触发

permissions:
  contents: write
  packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ] # 需要打包的系统
        goarch: [ amd64, arm64 ] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.5
        with:
          pre_command: export GODEBUG=http2client=0
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.0 # 可以指定编译使用的 Golang 版本
          project_path: "./cmd"
          binary_name: "aigo" # 可以指定二进制文件的名称
          extra_files: template.md # 需要包含的额外文件
