name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.2.2

      - name: Build binary
        run: go build -o aigo ./cmd/main.go

      - name: Package binary and template
        run: |
          mkdir -p release
          cp template.md release/
          cp aigo release/
          zip -r release_${{ matrix.os }}.zip release

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release_${{ matrix.os }}.zip
          asset_name: release_${{ matrix.os }}.zip
          asset_content_type: application/zip